# Generated by Django 5.0.4 on 2024-05-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='contentbody',
            new_name='content_body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='coverimage',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='resourceid',
            new_name='resource_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='coverimage',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='featuredid',
            new_name='featured_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='resourceid',
            new_name='resource_id',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='introContent',
            new_name='intro_content',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='profilePhoto',
            new_name='profile_photo',
        ),
    ]
