# Generated by Django 5.0.4 on 2024-05-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0002_rename_contentbody_blog_content_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='resource_id',
            new_name='blog_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='resource_id',
            new_name='category_id',
        ),
    ]
