# Generated by Django 5.0.4 on 2024-05-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0004_userdata_dark_theme_userdata_defaut_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='dark_theme',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='defaut_theme',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='light_theme',
            field=models.CharField(max_length=1500),
        ),
    ]
