# Generated by Django 5.0.4 on 2024-05-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0005_alter_userdata_dark_theme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='defaut_theme',
            new_name='default_theme',
        ),
    ]
