# Generated by Django 5.0.4 on 2024-05-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0006_rename_defaut_theme_userdata_default_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
