# Generated by Django 5.0.4 on 2024-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0007_alter_category_featured_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='dark_theme',
            field=models.CharField(default='{"darkTheme": { "theme": "Dark Mode","background": "bg-dark","textColor": "text-white","linkBackground": "bg-light","linkTextColor": "text-black","captionColor": "#8a8a8a","fontAwesomeIcon": "faSun","borderColor": "secondary","buttonColor": "light","navBar": {"navBarTheme": "navbar-dark","background": "bg-secondary","buttonColor": "light"},"footer": {"background": "bg-secondary","text": "bg-white"}}}', max_length=1500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='default_theme',
            field=models.CharField(default='darkTheme', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='intro_content',
            field=models.CharField(default='<p>Write something about yourself</p>', max_length=100000),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='light_theme',
            field=models.CharField(default='{"lightTheme":{"theme": "Light Mode","background": "bg-light","textColor": "text-black","linkBackground": "bg-dark","linkTextColor": "text-white","captionColor": "#605f5f","fontAwesomeIcon": "faMoon","borderColor": "secondary","buttonColor": "dark","navBar": {"navBarTheme": "navbar-light","background": "bg-secondary","buttonColor": "light"},"footer": {"background": "bg-secondary","text": "bg-white"}}}', max_length=1500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='Jhon Doe', max_length=200),
        ),
    ]
