# Generated by Django 5.0.4 on 2024-05-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0009_alter_blog_content_body_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='parent_category',
        ),
    ]
