# Generated by Django 5.0.6 on 2024-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0013_auto_20240609_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='John Doe', max_length=200),
        ),
    ]
